<?php declare(strict_types = 1);

namespace Tests\Feature\Controller\Account;

use App\Models\Account\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

/**
 * Class AccountControllerTest
 * @package Tests\Feature\Controller\Account
 */
class AccountControllerTest extends TestCase
{
    use DatabaseTransactions;

    private $user;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
    }

    /**
     * @covers \App\Http\Controllers\Web\User\AccountController::showAccountView()
     * @covers \App\Http\Middleware\RedirectIfAuthenticated
     */
    public function testAccountView()
    {
        $response = $this->actingAs($this->user)->get('account');
        $response->assertStatus(200);
    }

    /**
     * @covers \App\Http\Controllers\Web\User\AccountController::delete()
     */
    public function testDeleteAccount()
    {
        $response = $this->actingAs($this->user)->delete('account', []);
        $response->assertStatus(302);
    }

    /**
     * @covers \App\Http\Controllers\Web\User\AccountController::showEditAccountView()
     */
    public function testAccountEditFormView()
    {
        $response = $this->actingAs($this->user)->get('account/edit');
        $response->assertStatus(200);
    }

    /**
     * @covers \App\Http\Controllers\Web\User\AccountController::updateAccount()
     * @covers \App\Http\Middleware\VerifyCsrfToken
     */
    public function testUpdateAccount()
    {
        $response = $this->actingAs($this->user)->patch('account', [
            'name' => 'UpdatedName',
            'email' => 'a'.str_random(5).'@star-citizen.wiki',
            'password' => null,
            'password_confirmed' => null,
        ]);

        $response->assertStatus(302);
    }
}
