image: php:7.1

cache:
  paths:
  - vendor/

before_script:
- bash ci/docker_install.sh > /dev/null
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- php composer.phar update
- touch database/users.sqlite
- php artisan migrate --env=testing
- php artisan db:seed --env=testing

phpunit:
  script:
  - vendor/bin/phpunit --coverage-text --colors=never --configuration phpunit.xml