image: php:7.1.3

cache:
  paths:
  - vendor/

before_script:
- bash ci/docker_install.sh > /dev/null
- curl -sS https://getcomposer.org/installer | php
- mv .env.testing .env
- php composer.phar install
- php composer.phar update
- touch database/api.sqlite
- php artisan migrate
- php artisan db:seed

phpunit:
  script:
  - vendor/bin/phpunit --coverage-text --colors=never --configuration phpunit.xml