<?php

namespace Tests\Feature\Controller\Admin;

use App\Models\ShortURL\ShortURL;
use App\Models\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

/**
 * Class AdminControllerTest
 * @package Tests\Feature\Controller
 */
class AdminControllerTest extends TestCase
{
    use DatabaseTransactions;

    private $user;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::find(1);
    }

    /**
     * @covers \App\Http\Controllers\Auth\Admin\AdminController::showRoutesView()
     */
    public function testRoutesView()
    {
        $response = $this->actingAs($this->user)->get('admin/routes');
        $response->assertStatus(200);
    }
}
