<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\WithoutEvents;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class AccountControllerTest extends TestCase
{
    use DatabaseTransactions, WithoutMiddleware;

    private $user;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::showAccountView()
     */
    public function testAccountView()
    {
        $response = $this->actingAs($this->user)->get('account');
        $response->assertStatus(200);
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::showEditAccountView()
     */
    public function testAccountEditFormView()
    {
        $response = $this->actingAs($this->user)->get('account/edit');
        $response->assertStatus(200);
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::showURLsView()
     */
    public function testURLView()
    {
        $response = $this->actingAs($this->user)->get('account/urls');
        $response->assertStatus(200);
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::showAddURLView()
     */
    public function testURLAddView()
    {
        $response = $this->actingAs($this->user)->get('account/urls/add');
        $response->assertStatus(200);
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::addURL()
     */
    public function testAddURL()
    {
        $response = $this->actingAs($this->user)->post('account/urls', [
            'url' => 'https://star-citizen.wiki/'.str_random(4),
            'hash_name' => str_random(4),
        ]);
        $response->assertStatus(302);
        $response->assertRedirect('account/urls');
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::addURL()
     */
    public function testAddURLException()
    {
        $response = $this->actingAs($this->user)->post('account/urls', [
            'url' => 'https://notwhitelisted.wiki/'.str_random(4),
            'hash_name' => str_random(4),
        ]);
        $response->assertStatus(302);
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::deleteURL()
     */
    public function testDeleteURL()
    {
        $response = $this->actingAs($this->user)->delete('account/urls', [
            'id' => 1,
        ]);
        $response->assertStatus(302);
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::showEditURLView()
     */
    public function testEditURLViewNotExist()
    {
        $response = $this->actingAs($this->user)->get('account/urls/-1');
        $response->assertStatus(302);
    }

    /**
     * @covers \App\Http\Controllers\Auth\AccountController::delete()
     */
    public function testeDeleteAccount()
    {
        $response = $this->actingAs($this->user)->delete('account', []);
        $response->assertStatus(302);
    }
}
