<?php

namespace Tests\Feature;

use App\Exceptions\InvalidDataException;
use App\Repositories\StarCitizenWiki\APIv1\Ships\ShipsRepository;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

/**
 * Class FiltersDataTraitTest
 * @package Tests\Feature
 */
class FiltersDataTraitTest extends TestCase
{
    /**
     * @var ShipsRepository
     */
    private $repository;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = resolve(ShipsRepository::class);
    }

    /**
     * Test if InvalidDataException is thrown if unknown field is filtered
     *
     * @covers \App\Traits\FiltersDataTrait::filterData()
     */
    public function testFilterException()
    {
        $this->repository->getShipList();
        $this->expectException(InvalidDataException::class);
        $this->repository->transformer->addFilterArray(['notexists']);
        $this->repository->asJSON();
    }
}
