<?php

declare(strict_types=1);

use Illuminate\Support\Facades\File;
use Symfony\Component\Yaml\Yaml;

describe('OpenAPI specification', function (): void {
    beforeEach(function (): void {
        $this->yaml = File::get(base_path('swagger.yaml'));
        $this->spec = Yaml::parse($this->yaml);
    });

    it('contains stable operation IDs', function (string $operationId): void {
        expect($this->yaml)->toContain("operationId: {$operationId}");
    })->with([
        'searchGameData',
        'resolveSearchQuery',
        'getOpenApiSpec',
        'listVehicles',
        'getVehicle',
        'getGroundVehicle',
        'getGravlevVehicle',
        'listItems',
        'getItem',
        'getWeapon',
        'getWeaponAttachment',
        'getClothingItem',
        'getArmor',
        'getFood',
        'getVehicleWeapon',
        'getVehicleItem',
        'listCommodities',
        'getCommodity',
        'getDefaultGameVersion',
        'listGameVersions',
        'getGameVersion',
        'listMissions',
        'getMission',
        'listLocations',
        'getLocation',
        'listBlueprints',
        'getBlueprint',
        'listManufacturers',
        'getManufacturer',
        'listFactions',
        'getFaction',
        'listCommLinks',
        'getCommLink',
        'listStats',
        'getLatestStats',
        'getAuthenticatedUser',
        'findSimilarImages',
    ]);

    it('has no autogenerated hash-like operation IDs', function (): void {
        preg_match_all('/operationId:\s+([a-f0-9]{16,})/', $this->yaml, $matches);
        expect($matches[0])->toBeEmpty('Found hash-like operation IDs: '.implode(', ', $matches[1]));
    });

    it('has no duplicate operation IDs', function (): void {
        preg_match_all('/operationId:\s+(\S+)/', $this->yaml, $matches);
        $ids = $matches[1];
        $duplicates = array_filter(array_count_values($ids), fn (int $count): bool => $count > 1);
        expect($duplicates)->toBeEmpty('Duplicate operation IDs found: '.implode(', ', array_keys($duplicates)));
    });

    it('defines the sanctum security scheme without JWT wording', function (): void {
        expect($this->yaml)->toContain('securitySchemes:');
        expect($this->yaml)->toContain('sanctum:');
        expect($this->yaml)->not->toContain('bearerFormat');
    });

    it('defines the version parameter', function (): void {
        expect($this->yaml)->toContain('#/components/parameters/version');
    });

    it('contains pagination schemas', function (): void {
        expect($this->yaml)->toContain('pagination_links');
        expect($this->yaml)->toContain('pagination_meta');
    });

    it('contains error response schemas', function (string $schema): void {
        expect($this->yaml)->toContain($schema);
    })->with([
        'error_response',
        'validation_error_response',
        'not_found_error_response',
        'rate_limit_error_response',
        'unauthenticated_error_response',
    ]);

    it('contains named developer onboarding examples', function (string $exampleName): void {
        expect($this->yaml)->toContain("{$exampleName}:");
    })->with([
        'ship_search',
        'ship_search_results',
        'search_carrack',
        'vehicle_search_page',
        'item_search_page',
        'location_arccorp',
        'commodities_by_location',
        'default_game_version',
        'delivery_missions',
        'delivery_mission_page',
    ]);

    it('documents the public user fields returned by /api/user', function (): void {
        $userSchema = $this->spec['paths']['/api/user']['get']['responses'][200]['content']['application/json']['schema']['properties'] ?? [];

        expect($userSchema)->toHaveKeys([
            'id',
            'name',
            'email',
            'email_verified_at',
            'is_admin',
            'language_id',
            'created_at',
            'updated_at',
        ]);
    });

    it('documents 429 on all throttled endpoints with JSON content', function (string $operationId): void {
        $spec = $this->spec;
        $found = false;
        foreach ($spec['paths'] as $pathItem) {
            foreach ($pathItem as $method => $op) {
                if (is_array($op) && ($op['operationId'] ?? '') === $operationId) {
                    $r429 = $op['responses'][429] ?? $op['responses']['429'] ?? null;
                    expect($r429)->not->toBeNull("Expected 429 response on {$operationId}");
                    $schema = $r429['content']['application/json']['schema']['$ref'] ?? null;
                    expect($schema)->toBe('#/components/schemas/rate_limit_error_response', "Expected rate_limit_error_response ref on {$operationId}");
                    $found = true;
                }
            }
        }
        expect($found)->toBeTrue("Operation {$operationId} not found in spec");
    })->with([
        'searchGameData',
        'reverseImageLinkSearch',
        'reverseImageSearch',
        'findSimilarImages',
    ]);

    it('marks deprecated endpoints as deprecated', function (): void {
        preg_match_all('/operationId:\s+(\w+Deprecated)/', $this->yaml, $matches);
        expect($matches[1])->not->toBeEmpty('No deprecated endpoints found');

        foreach ($matches[1] as $deprecatedOpId) {
            $pattern = "/operationId:\s+{$deprecatedOpId}\n.*?deprecated:\s+true/s";
            expect($this->yaml)->toMatch($pattern, "Deprecated endpoint {$deprecatedOpId} should have deprecated: true");
        }
    });

    it('does not use broad In-Game or RSI-Website tags', function (): void {
        expect($this->yaml)->not->toContain("'In-Game'");
        expect($this->yaml)->not->toContain("'RSI-Website'");
    });

    it('documents 404 with shared schema on every detail endpoint', function (string $operationId): void {
        $spec = $this->spec;
        $found = false;
        foreach ($spec['paths'] as $pathItem) {
            foreach ($pathItem as $method => $op) {
                if (is_array($op) && ($op['operationId'] ?? '') === $operationId) {
                    $r404 = $op['responses'][404] ?? $op['responses']['404'] ?? null;
                    expect($r404)->not->toBeNull("Missing 404 response on {$operationId}");
                    $content = $r404['content']['application/json']['schema']['$ref'] ?? null;
                    expect($content)->toBe('#/components/schemas/not_found_error_response', "Expected not_found_error_response ref on {$operationId}, got: ".json_encode($r404));
                    $found = true;
                }
            }
        }
        expect($found)->toBeTrue("Operation {$operationId} not found in spec");
    })->with([
        'getVehicle',
        'getGroundVehicle',
        'getGravlevVehicle',
        'getItem',
        'getWeapon',
        'getWeaponAttachment',
        'getClothingItem',
        'getArmor',
        'getFood',
        'getVehicleWeapon',
        'getVehicleItem',
        'getCommodity',
        'getManufacturer',
        'getGameVersion',
        'getDefaultGameVersion',
        'getBlueprint',
        'getFaction',
        'getMission',
        'getLocation',
        'getCommLink',
        'getGalactapediaArticle',
        'getCelestialObject',
        'getStarsystem',
        'getVersionChangelog',
        'listVersionChangelogChanges',
    ]);

    it('documents auth and 401 on protected endpoints', function (string $operationId): void {
        $spec = $this->spec;
        $found = false;
        foreach ($spec['paths'] as $pathItem) {
            foreach ($pathItem as $method => $op) {
                if (is_array($op) && ($op['operationId'] ?? '') === $operationId) {
                    $security = $op['security'] ?? null;
                    expect($security)->not->toBeNull("Expected security declaration on {$operationId}");
                    $r401 = $op['responses'][401] ?? $op['responses']['401'] ?? null;
                    expect($r401)->not->toBeNull("Expected 401 response on {$operationId}");
                    $content = $r401['content']['application/json']['schema']['$ref'] ?? null;
                    expect($content)->toBe('#/components/schemas/unauthenticated_error_response', "Expected unauthenticated_error_response ref on {$operationId}");
                    $found = true;
                }
            }
        }
        expect($found)->toBeTrue("Operation {$operationId} not found in spec");
    })->with([
        'getAuthenticatedUser',
        'findSimilarImages',
    ]);

    it('uses data envelope on stats latest', function (): void {
        $spec = $this->spec;
        foreach ($spec['paths'] as $pathItem) {
            foreach ($pathItem as $method => $op) {
                if (is_array($op) && ($op['operationId'] ?? '') === 'getLatestStats') {
                    $schema = $op['responses'][200]['content']['application/json']['schema'] ?? null;
                    expect($schema)->not->toBeNull();
                    expect($schema)->toHaveKey('properties');
                    expect($schema['properties'])->toHaveKey('data');
                }
            }
        }
    });

    it('does not document v2/v3 compatibility routes', function (): void {
        $spec = $this->spec;
        foreach ($spec['paths'] as $path => $pathItem) {
            expect($path)->not->toStartWith('/api/v2/', "Unexpected v2 route in spec: {$path}");
            expect($path)->not->toStartWith('/api/v3/', "Unexpected v3 route in spec: {$path}");
        }
    });
});
