<?php

namespace Tests\Feature;

use App\Repositories\StarCitizenWiki\APIv1\Ships\ShipsRepository;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

/**
 * Class ShipsTest
 * @package Tests\Feature
 */
class ShipsRepositoryTest extends TestCase
{
    /**
     * @var ShipsRepository
     */
    private $repository;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = resolve(ShipsRepository::class);
    }

    /**
     * Get Ship from Repository
     *
     * @covers \App\Repositories\StarCitizenWiki\APIv1\Ships\ShipsRepository::getShip()
     */
    public function testShipRetrieval()
    {
        $this->repository->getShip('300i');
        $this->assertContains('300i', $this->repository->asJSON());
    }

    /**
     * @covers \App\Repositories\StarCitizenWiki\APIv1\Ships\ShipsRepository::getShipList()
     */
    public function testShipList()
    {
        $this->repository->getShipList();
        $this->assertContains('300i', $this->repository->asJSON());
    }

    /**
     * @covers \App\Repositories\StarCitizenWiki\APIv1\Ships\ShipsRepository::searchShips()
     */
    public function testShipSearch()
    {
        $this->repository->searchShips('300i');
        $this->assertContains('300i', $this->repository->asJSON());
    }

    /**
     * Test if Filter is working
     *
     * @covers \App\Repositories\StarCitizenWiki\APIv1\Ships\ShipsRepository::getShipList()
     */
    public function testFilter()
    {
         $this->repository->getShipList();
         $this->repository->transformer->addFilterArray(['api_url']);
         $this->assertNotContains('"wiki_url":', $this->repository->asJSON());
    }
}
