<?php

namespace Tests\Feature;

use App\Repositories\StarCitizenWiki\APIv1\Ships\ShipsRepository;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

/**
 * Class ShipsTest
 * @package Tests\Feature
 */
class ShipsTest extends TestCase
{
    /**
     * @var ShipsRepository
     */
    private $repository;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = resolve(ShipsRepository::class);
    }

    /**
     * Get Ship from API
     */
    public function testApiShipView()
    {
        $response = $this->get('api/v1/ships/300i');
        $response->assertSee('300i');
    }

    /**
     * Test Search
     */
    public function testSearch()
    {
        $response = $this->post('api/v1/search', ['300i']);
        $response->assertSee('300i');
    }

    /**
     * Get Ship from Repository
     */
    public function testShipRetrieval()
    {
        $this->repository->getShip('300i');
        $this->assertContains('300i', $this->repository->asJSON());
    }

    /**
     * Test if Filter is working
     */
    public function testFilter()
    {
         $this->repository->getShipList();
         $this->repository->transformer->addFilterArray(['api_url']);
         $this->assertNotContains('"wiki_url":', $this->repository->asJSON());
    }
}
