<?php

namespace Tests\Feature;

use App\Exceptions\URLNotWhitelistedException;
use App\Models\ShortURL\ShortURL;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ShortURLModelTest extends TestCase
{
    use DatabaseTransactions;

    private $url;
    private $hashName;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->url = 'https://star-citizen.wiki/'.str_random(16);
        $this->hashName = str_random(6);
    }

    /**
     * Test not WhitelistedException
     *
     * @covers ShortURL::createShortURL()
     */
    public function testNotWhitelistedException()
    {
        $this->expectException(URLNotWhitelistedException::class);
        ShortURL::createShortURL(['url' => 'https://notwhitelisted.com']);
    }

    /**
     * Test NotFound Exception
     *
     * @covers ShortURL::resolve()
     */
    public function testHashNotExistsException()
    {
        $this->expectException(ModelNotFoundException::class);
        ShortURL::resolve('Does_Not_Exist');
    }

    /**
     * Test Repository Creation
     *
     * @covers ShortURL::createShortURL()
     */
    public function testShortURLCreation()
    {
        $url = ShortURL::createShortURL([
            'url' => $this->url,
            'hash_name' => $this->hashName,
            'user_id' => 1,
        ]);

        $this->assertEquals($this->hashName, $url->hash_name);
    }

    /**
     * @covers ShortURL::sanitizeURL()
     */
    public function testURLSanitization()
    {
        $url = 'https://star-citizen.wiki';
        $urlSanitized = ShortURL::sanitizeURL($url);

        $this->assertEquals($url.'/', $urlSanitized);
    }
}
