<?php

namespace Tests\Feature;

use App\Http\Controllers\Auth\RegisterController;
use App\Models\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class UserTest extends TestCase
{
    use DatabaseTransactions;

    /** @var  RegisterController */
    private $_api;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->_api = resolve(RegisterController::class);
    }

    public function testAccountCreation()
    {
        $name = str_random(6);
        $email = strtolower($name).'@'.strtolower($name).'.de';
        $user = $this->_api->create([
            'name' => $name,
            'email' => $email,
            'api_token' => str_random(60),
            'password' => bcrypt($name),
            'requests_per_minute' => 60,
            'last_login' => date('Y-m-d H:i:s'),
        ]);

        $this->assertEquals($email, $user->email);
    }
}
