<?php declare(strict_types = 1);

namespace Tests\Feature\Model;

use App\Exceptions\UrlNotWhitelistedException;
use App\Models\ShortUrl\ShortUrl;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

/**
 * Class ShortUrlModelTest
 * @package Tests\Feature\Model
 */
class ShortUrlModelTest extends TestCase
{
    use DatabaseTransactions;

    private $url;
    private $hashName;

    /**
     * Test not WhitelistedException
     *
     * @covers \App\Models\ShortUrl\ShortUrl::createShortUrl()
     * @covers \App\Exceptions\UrlNotWhitelistedException
     */
    public function testNotWhitelistedException()
    {
        $this->expectException(UrlNotWhitelistedException::class);
        ShortUrl::create(
            [
                'url'        => 'https://notwhitelisted.com',
                'hash'       => $this->hashName,
                'user_id'    => 1,
                'expired_at' => null,
            ]
        );
    }

    /**
     * Test Repository Creation
     *
     * @covers \App\Models\ShortUrl\ShortUrl::createShortUrl()
     */
    public function testShortUrlCreation()
    {
        $url = ShortUrl::create(
            [
                'url'        => $this->url,
                'hash'       => $this->hashName,
                'user_id'    => 1,
                'expired_at' => null,
            ]
        );

        $this->assertEquals($this->hashName, $url->hash);
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->url = 'https://star-citizen.wiki/'.str_random(16);
        $this->hashName = str_random(6);
    }
}
