<?php

declare(strict_types=1);

namespace App\Http\Resources\Game\Item;

use App\Http\Resources\AbstractBaseResource;
use App\Http\Resources\Game\Concerns\ExtractsJsonData;
use App\Http\Resources\Game\ItemSpecification\AmmunitionResource;
use App\Http\Resources\Game\ItemSpecification\ArmorResource;
use App\Http\Resources\Game\ItemSpecification\BarrelAttachmentResource;
use App\Http\Resources\Game\ItemSpecification\BombResource;
use App\Http\Resources\Game\ItemSpecification\CargoGridResource;
use App\Http\Resources\Game\ItemSpecification\CharacterArmorResource;
use App\Http\Resources\Game\ItemSpecification\ClothingResource;
use App\Http\Resources\Game\ItemSpecification\CoolerResource;
use App\Http\Resources\Game\ItemSpecification\CounterMeasureResource;
use App\Http\Resources\Game\ItemSpecification\EmpResource;
use App\Http\Resources\Game\ItemSpecification\FlightControllerResource;
use App\Http\Resources\Game\ItemSpecification\FoodResource;
use App\Http\Resources\Game\ItemSpecification\FuelIntakeResource;
use App\Http\Resources\Game\ItemSpecification\FuelTankResource;
use App\Http\Resources\Game\ItemSpecification\GrenadeResource;
use App\Http\Resources\Game\ItemSpecification\HackingChipResource;
use App\Http\Resources\Game\ItemSpecification\IronSightResource;
use App\Http\Resources\Game\ItemSpecification\MeleeWeaponResource;
use App\Http\Resources\Game\ItemSpecification\MiningLaserResource;
use App\Http\Resources\Game\ItemSpecification\MiningModuleResource;
use App\Http\Resources\Game\ItemSpecification\MissileRackResource;
use App\Http\Resources\Game\ItemSpecification\MissileResource;
use App\Http\Resources\Game\ItemSpecification\PersonalWeaponResource;
use App\Http\Resources\Game\ItemSpecification\PowerPlantResource;
use App\Http\Resources\Game\ItemSpecification\QuantumDriveResource;
use App\Http\Resources\Game\ItemSpecification\QuantumInterdictionGeneratorResource;
use App\Http\Resources\Game\ItemSpecification\RadarResource;
use App\Http\Resources\Game\ItemSpecification\RadiationResistanceResource;
use App\Http\Resources\Game\ItemSpecification\SalvageModifierResource;
use App\Http\Resources\Game\ItemSpecification\SelfDestructResource;
use App\Http\Resources\Game\ItemSpecification\ShieldResource;
use App\Http\Resources\Game\ItemSpecification\TemperatureResistanceResource;
use App\Http\Resources\Game\ItemSpecification\ThrusterResource;
use App\Http\Resources\Game\ItemSpecification\TractorBeamResource;
use App\Http\Resources\Game\ItemSpecification\VehicleWeaponResource;
use App\Http\Resources\Game\ItemSpecification\WeaponAttachmentResource;
use App\Http\Resources\Game\ItemSpecification\WeaponModifierResource;
use App\Http\Resources\Game\Manufacturer\ManufacturerLinkResource;
use App\Models\Game\Item;
use App\Models\Game\ItemData;
use App\Models\Game\ItemTranslation;
use App\Services\RelatedItemsBuilder;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use OpenApi\Attributes as OA;

#[OA\Schema(
    schema: 'item_base',
    title: 'Item',
    description: 'An item in Star Citizen, based on EntityClassDefinition XML files.',
    properties: [
        new OA\Property(property: 'uuid', type: 'string'),
        new OA\Property(property: 'name', type: 'string'),
        new OA\Property(property: 'class_name', type: 'string'),
        new OA\Property(property: 'classification', description: 'Not actually found in the game data, but generated by ScDataDumper.', type: 'string', example: 'FPS.Clothing.Torso'),
        new OA\Property(
            property: 'description',
            nullable: true,
            oneOf: [
                new OA\Schema(type: 'string'),
                new OA\Schema(
                    type: 'array',
                    items: new OA\Items(ref: '#/components/schemas/translation_v2'),
                ),
            ],
        ),
        new OA\Property(property: 'size',
            description: 'AttachDef@Size', type: 'integer', example: 1, nullable: true),
        new OA\Property(property: 'mass',
            description: 'Generated from SEntityRigidPhysicsControllerParams', type: 'double', example: 1000.0, nullable: true),
        new OA\Property(property: 'is_base_variant', type: 'boolean'),
        new OA\Property(property: 'grade', type: 'string', nullable: true),
        new OA\Property(property: 'class', type: 'string', nullable: true),
        new OA\Property(
            property: 'description_data',
            description: 'Key Value pairs from the description, where key is data before a ":" and value is whats following',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_description_data'),
            nullable: true
        ),
        new OA\Property(property: 'manufacturer_description', description: 'Manufacturer set in the description', type: 'string', nullable: true),
        new OA\Property(property: 'manufacturer', ref: '#/components/schemas/manufacturer_link'),
        new OA\Property(property: 'type', description: 'AttachDef@Type', type: 'string', nullable: true),
        new OA\Property(property: 'sub_type', description: 'AttachDef@SubType', type: 'string', nullable: true),
        new OA\Property(property: 'dimension', ref: '#/components/schemas/item_dimension'),
        new OA\Property(property: 'inventory', ref: '#/components/schemas/item_container', nullable: true),
        new OA\Property(
            property: 'tags',
            description: 'AttachDef@Tags',
            type: 'array',
            items: new OA\Items(type: 'string'),
            nullable: true,
        ),
        new OA\Property(
            property: 'required_tags',
            description: 'AttachDef@RequiredTags',
            type: 'array',
            items: new OA\Items(type: 'string'),
            nullable: true,
        ),
        new OA\Property(
            property: 'entity_tags',
            description: 'Generated from EntityClassDefinition/tags',
            type: 'array',
            items: new OA\Items(type: 'string'),
            nullable: true,
        ),
        new OA\Property(
            property: 'entity_tag_map',
            description: 'Entity tags from the database relationship',
            type: 'array',
            items: new OA\Items(
                properties: [
                    new OA\Property(property: 'uuid', type: 'string'),
                    new OA\Property(property: 'name', type: 'string'),
                ],
                type: 'object'
            ),
            nullable: true,
        ),
        new OA\Property(
            property: 'interactions',
            description: 'Generated from SInteractionPointParams',
            type: 'array',
            items: new OA\Items(type: 'string'),
            nullable: true,
        ),
        new OA\Property(
            property: 'item_ports',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_port'),
            nullable: true
        ),
        new OA\Property(property: 'heat', ref: '#/components/schemas/item_heat_connection', nullable: true),
        new OA\Property(property: 'power', ref: '#/components/schemas/item_power_connection', nullable: true),
        new OA\Property(property: 'distortion', ref: '#/components/schemas/item_distortion', nullable: true),
        new OA\Property(property: 'durability', ref: '#/components/schemas/item_durability', nullable: true),
        new OA\Property(property: 'resource_container', ref: '#/components/schemas/resource_container', nullable: true),
        new OA\Property(property: 'ammunition', ref: '#/components/schemas/ammunition', nullable: true),

        new OA\Property(property: 'temperature_resistance', ref: '#/components/schemas/temperature_resistance', nullable: true),
        new OA\Property(property: 'radiation_resistance', ref: '#/components/schemas/radiation_resistance', nullable: true),
        new OA\Property(property: 'armor', ref: '#/components/schemas/vehicle_armor', nullable: true),
        new OA\Property(property: 'cooler', ref: '#/components/schemas/cooler', nullable: true),
        new OA\Property(property: 'flight_controller', ref: '#/components/schemas/flight_controller', nullable: true),
        new OA\Property(property: 'fuel_tank', ref: '#/components/schemas/fuel_tank', nullable: true),
        new OA\Property(property: 'hacking_chip', ref: '#/components/schemas/hacking_chip', nullable: true),
        new OA\Property(property: 'mining_laser', ref: '#/components/schemas/mining_laser', nullable: true),
        new OA\Property(property: 'mining_module', ref: '#/components/schemas/mining_module', nullable: true),
        new OA\Property(property: 'quantum_drive', ref: '#/components/schemas/quantum_drive', nullable: true),
        new OA\Property(property: 'quantum_interdiction_generator', ref: '#/components/schemas/quantum_interdiction_generator', nullable: true),
        new OA\Property(property: 'self_destruct', ref: '#/components/schemas/self_destruct', nullable: true),
        new OA\Property(property: 'shield', ref: '#/components/schemas/shield', nullable: true),
        new OA\Property(property: 'resource_network', ref: '#/components/schemas/resource_network', nullable: true),
        new OA\Property(property: 'thruster', ref: '#/components/schemas/thruster', nullable: true),

        // Item Specifications
        new OA\Property(property: 'clothing', ref: '#/components/schemas/clothing', nullable: true),
        new OA\Property(property: 'character_armor', ref: '#/components/schemas/character_armor', nullable: true),
        new OA\Property(property: 'suit_armor', ref: '#/components/schemas/character_armor', nullable: true, deprecated: true),
        new OA\Property(property: 'bomb', ref: '#/components/schemas/bomb', nullable: true),
        new OA\Property(property: 'missile', ref: '#/components/schemas/missile', nullable: true),
        new OA\Property(property: 'emp', ref: '#/components/schemas/emp', nullable: true),
        new OA\Property(property: 'personal_weapon', ref: '#/components/schemas/personal_weapon', nullable: true),
        new OA\Property(property: 'melee_weapon', ref: '#/components/schemas/melee_weapon', nullable: true),
        new OA\Property(property: 'grenade', ref: '#/components/schemas/grenade', nullable: true),
        new OA\Property(property: 'knife', ref: '#/components/schemas/melee_weapon', nullable: true, deprecated: true),
        new OA\Property(property: 'barrel_attach', ref: '#/components/schemas/barrel_attachment', nullable: true),
        new OA\Property(property: 'weapon_modifier', ref: '#/components/schemas/weapon_modifier', nullable: true),
        new OA\Property(property: 'iron_sight', ref: '#/components/schemas/iron_sight', nullable: true),
        new OA\Property(property: 'salvage_modifier', ref: '#/components/schemas/salvage_modifier', nullable: true),

        new OA\Property(property: 'base_variant', ref: '#/components/schemas/item_link', nullable: true),
        new OA\Property(
            property: 'variants',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_link'),
            nullable: true
        ),
        new OA\Property(
            property: 'updated_at',
            description: 'Date time this item was updated in the database',
            type: 'datetime',
        ),
        new OA\Property(
            property: 'version',
            description: 'Game version code',
            type: 'string',
            example: '4.4.0-LIVE.12340123'
        ),
    ],
    type: 'object'
)]

#[OA\Schema(
    schema: 'item_related_link_v2',
    title: 'Related Item Link',
    description: 'Minimal link information for a related item',
    properties: [
        new OA\Property(property: 'uuid', type: 'string'),
        new OA\Property(property: 'name', type: 'string'),
        new OA\Property(property: 'variant_name', type: 'string', nullable: true),
        new OA\Property(property: 'link', type: 'string'),
    ],
    type: 'object'
)]

#[OA\Schema(
    schema: 'item_related_link_ext_v2',
    title: 'Related Item Link (Extended)',
    description: 'Related item link with basic classification',
    allOf: [
        new OA\Schema(ref: '#/components/schemas/item_related_link_v2'),
        new OA\Schema(
            properties: [
                new OA\Property(property: 'type', type: 'string', nullable: true),
                new OA\Property(property: 'sub_type', type: 'string', nullable: true),
            ],
            type: 'object'
        ),
    ],
)]

#[OA\Schema(
    schema: 'item_related_items_v2',
    title: 'Related Items',
    description: 'Aggregated related information for base/variants and set items',
    properties: [
        new OA\Property(property: 'set_name', type: 'string', nullable: true),
        new OA\Property(property: 'base_item', ref: '#/components/schemas/item_related_link_v2', nullable: true),
        new OA\Property(
            property: 'variant_items',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_related_link_v2'),
            nullable: true,
        ),
        new OA\Property(
            property: 'set_items',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_related_link_ext_v2'),
            nullable: true,
        ),
    ],
    type: 'object'
)]
class ItemResource extends AbstractBaseResource
{
    use ExtractsJsonData;

    public static function validIncludes(): array
    {
        return [
            'variants',
            // 'related_items', // Set in Controller
        ];
    }

    public function toArray(Request $request): array
    {
        if ($this->uuid === null) {
            return [];
        }

        $this->addMetadata('deprecations', [
            'shops' => 'Shop data is not available in the source files anymore, there is currently no replacement.',
        ]);

        $itemData = $this->data->first();

        // Determine if 'related_items' has been requested via include
        $includeParam = $request->query('include');
        $includeValues = [];
        if (is_string($includeParam)) {
            $includeValues = array_map('trim', explode(',', $includeParam));
        } elseif (is_array($includeParam)) {
            $includeValues = $includeParam;
        }
        $includeRelated = in_array('related_items', $includeValues, true);

        return [
            'uuid' => $this->uuid,
            'name' => $itemData->name,
            'class_name' => $itemData->class_name,
            'classification' => $itemData->classification,
            'description' => $this->getTranslation($itemData, $request),
            'size' => $itemData->size,
            'mass' => $this->extractNumeric($itemData, 'Mass'),
            'is_base_variant' => $itemData->base_id === null,
            $this->mergeWhen(str_starts_with($itemData->classification ?? '', 'Ship.'), [
                'grade' => match ($itemData->grade) {
                    1 => 'A',
                    2 => 'B',
                    3 => 'C',
                    4 => 'D',
                    default => $itemData->grade,
                },
                'class' => $itemData->class,
            ]),
            'description_data' => ItemDescriptionDataResource::collection($itemData->descriptionData),
            'manufacturer_description' => $itemData->getDescriptionDatum('Manufacturer'),
            'manufacturer' => new ManufacturerLinkResource($itemData->manufacturer),
            'type' => str_replace('NOITEM_', '', ($itemData->type ?? '')),
            'sub_type' => $itemData->sub_type,
            $this->mergeWhen(...$this->addAttachmentPosition($itemData)),
            $this->mergeWhen($this->isTurret($itemData), $this->addTurretData($itemData)),
            $this->mergeWhen(...$this->addSpecification($this->resource, $itemData)),
            'dimension' => new ItemDimensionResource($itemData),

            $this->mergeWhen($this->hasInStdItem($itemData, 'InventoryContainer'), [
                'inventory' => new ItemInventoryResource($this->extractFromStdItem($itemData, 'InventoryContainer')),
            ]),

            'tags' => $this->extractArray($itemData, 'Tags'),
            'required_tags' => $this->extractArray($itemData, 'RequiredTags'),
            'entity_tags' => $itemData->relationLoaded('entityTags')
                ? $itemData->entityTags->pluck('uuid')->values()->toArray()
                : [],
            'entity_tag_map' => $itemData->relationLoaded('entityTags')
                ? $itemData->entityTags->map(fn ($tag) => [
                    'uuid' => $tag->uuid,
                    'name' => $tag->name,
                ])->values()->toArray()
                : [],
            'interactions' => $this->extractArray($itemData, 'Interactions'),
            'ports' => ItemPortResource::collection($this->when($this->hasInStdItem($itemData, 'Ports'), $this->extractPorts($itemData))),
            $this->mergeWhen($this->hasInStdItem($itemData, 'ResourceContainer'), [
                'resource_container' => new ResourceContainerResource($this->extractFromStdItem($itemData, 'ResourceContainer')),
            ]),
            $this->mergeWhen($this->hasSpecification($itemData, 'Ammunition'), [
                'ammunition' => new AmmunitionResource($itemData),
            ]),

            $this->mergeWhen($this->hasInStdItem($itemData, 'RadiationResistance'), [
                'radiation_resistance' => new RadiationResistanceResource($this->extractFromStdItem($itemData, 'RadiationResistance')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'TemperatureResistance'), [
                'temperature_resistance' => new TemperatureResistanceResource($this->extractFromStdItem($itemData, 'TemperatureResistance')),
            ]),

            $this->mergeWhen($this->hasInStdItem($itemData, 'HeatConnection'), [
                'heat' => new ItemHeatConnectionResource($this->extractFromStdItem($itemData, 'HeatConnection')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'PowerConnection'), [
                'power' => new ItemPowerConnectionResource($this->extractFromStdItem($itemData, 'PowerConnection')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'Durability') && $this->extractFromStdItem($itemData, 'Durability.Lifetime', 0) > 0, [
                'durability' => new ItemDurabilityResource($this->extractFromStdItem($itemData, 'Durability')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'Distortion'), [
                'distortion' => new ItemDistortionResource($this->extractFromStdItem($itemData, 'Distortion')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'ResourceNetwork'), [
                'resource_network' => new ResourceNetworkResource($itemData),
            ]),

            'shops' => [],
            $this->mergeWhen($itemData->base_id !== null && $itemData->relationLoaded('baseVariant'), [
                'base_variant' => $itemData->baseVariant?->item
                    ? new ItemLinkResource($itemData->baseVariant->item)
                    : $this->makeApiUrl(self::ITEMS_SHOW, $itemData->baseVariant?->item?->uuid ?? ''),
            ]),
            'variants' => $itemData->relationLoaded('variants')
                ? ItemLinkResource::collection(
                    $itemData->variants
                        ->filter(fn ($v) => $v->item !== null)
                        ->map(fn ($v) => $v->item)
                )
                : [],
            $this->mergeWhen($includeRelated, [
                'related_items' => (new RelatedItemsBuilder($itemData->gameVersion->code))->build($this->resource),
            ]),
            'updated_at' => $this->updated_at,
            'version' => $itemData->gameVersion->code,
        ];
    }

    protected function addSpecification(Item $item, ItemData $itemData): array
    {
        //        $specification = $this?->specification;
        //        if (! $specification?->exists || $specification === null) {
        //            return [false, []];
        //        }

        return match (true) {
            str_starts_with($itemData->classification ?? '', 'FPS.Clothing.') => [
                true,
                fn () => ['clothing' => new ClothingResource($itemData)],
            ],
            str_starts_with($itemData->classification ?? '', 'FPS.Armor.') => [
                true,
                fn () => [
                    'character_armor' => new CharacterArmorResource($itemData),
                    'suit_armor' => new CharacterArmorResource($itemData),
                ],
            ],
            str_starts_with($itemData->classification ?? '', 'Ship.Armor.') => [
                true,
                fn () => ['armor' => new ArmorResource($itemData)],
            ],
            str_starts_with($itemData->classification ?? '', 'Ship.MainThruster'),
            str_starts_with($itemData->classification ?? '', 'Ship.ManneuverThruster') => [
                true,
                fn () => ['thruster' => new ThrusterResource($itemData)],
            ],
            $itemData->type === 'FlightController' => [
                true,
                fn () => ['flight_controller' => new FlightControllerResource($itemData)],
            ],
            in_array($itemData->type, ['FuelTank', 'QuantumFuelTank', 'ExternalFuelTank'], true) => [
                true,
                fn () => ['fuel_tank' => new FuelTankResource($itemData)],
            ],
            $itemData->sub_type === 'Hacking' => [
                true,
                fn () => ['hacking_chip' => new HackingChipResource($itemData)],
            ],
            $itemData->type === 'WeaponMining' => [
                true,
                fn () => ['mining_laser' => new MiningLaserResource($itemData)],
            ],
            $itemData->type === 'MiningModifier' => [
                true,
                fn () => ['mining_module' => new MiningModuleResource($itemData)],
            ],
            $itemData->type === 'Gadget' && $this->extractFromStdItem($itemData, 'MiningModule') !== null => [
                true,
                fn () => ['mining_gadget' => new MiningModuleResource($itemData)],
            ],
            $itemData->type === 'QuantumDrive' => [
                true,
                fn () => ['quantum_drive' => new QuantumDriveResource($itemData)],
            ],
            $itemData->type === 'QuantumInterdictionGenerator' => [
                true,
                fn () => ['quantum_interdiction_generator' => new QuantumInterdictionGeneratorResource($itemData)],
            ],
            $itemData->type === 'SelfDestruct' => [
                true,
                fn () => ['self_destruct' => new SelfDestructResource($itemData)],
            ],
            $itemData->type === 'Bomb' => [
                true,
                fn () => ['bomb' => new BombResource($itemData)],
            ],
            $itemData->type === 'Torpedo',
            $itemData->type === 'Missile' => [
                true,
                fn () => ['missile' => new MissileResource($itemData)],
            ],
            $itemData->type === 'EMP' => [
                true,
                fn () => ['emp' => new EmpResource($itemData)],
            ],
            $itemData->type === 'Cooler' => [
                true,
                fn () => ['cooler' => new CoolerResource($itemData)],
            ],
            in_array($itemData->type, ['TractorBeam', 'TowingBeam'], true) => [
                true,
                fn () => ['tractor_beam' => new TractorBeamResource($itemData)],
            ],
            $itemData->type === 'Shield' => [
                true,
                fn () => ['shield' => new ShieldResource($itemData)],
            ],
            $itemData->type === 'WeaponPersonal' && $itemData->sub_type === 'Grenade' => [
                true,
                fn () => [
                    'grenade' => new GrenadeResource($itemData),
                    'personal_weapon' => new PersonalWeaponResource($itemData),
                ],
            ],
            $itemData->type === 'WeaponPersonal' && $itemData->sub_type === 'Knife' => [
                true,
                fn () => [
                    'melee_weapon' => new MeleeWeaponResource($itemData),
                    'knife' => new MeleeWeaponResource($itemData),
                ],
            ],
            $itemData->type === 'WeaponPersonal',
            str_starts_with($itemData->classification ?? '', 'FPS.Weapon.') => [
                true,
                fn () => ['personal_weapon' => new PersonalWeaponResource($itemData)],
            ],
            $this->hasInStdItem($itemData, 'SalvageModifier') => [
                true,
                fn () => ['salvage_modifier' => new SalvageModifierResource($itemData)],
            ],
            $itemData->type === 'WeaponAttachment' && $itemData->sub_type === 'Barrel' => [
                true,
                fn () => ['barrel_attach' => new BarrelAttachmentResource($itemData)],
            ],
            $this->hasInStdItem($itemData, 'WeaponModifier') => [
                true,
                fn () => ['weapon_modifier' => new WeaponModifierResource($itemData)],
            ],
            $this->hasInStdItem($itemData, 'WeaponAttachment.IronSight') => [
                true,
                fn () => ['iron_sight' => new IronSightResource($itemData)],
            ],
            $itemData->type === 'WeaponAttachment' || $this->hasInStdItem($itemData, 'WeaponAttachment') => [
                true,
                fn () => ['weapon_attachment' => new WeaponAttachmentResource($itemData)],
            ],
            in_array($itemData->type, ['Food', 'Bottle', 'Drink'], true) || $this->hasInStdItem($itemData, 'Food') => [
                true,
                fn () => ['food' => new FoodResource($itemData)],
            ],
            $itemData->type === 'WeaponDefensive' || str_contains($itemData->classification ?? '', 'WeaponDefensive') => [
                true,
                fn () => ['counter_measure' => new CounterMeasureResource($itemData)],
            ],
            ($itemData->type === 'MissileLauncher' && $itemData->sub_type === 'MissileRack') || str_contains($itemData->classification ?? '', 'MissileRack') => [
                true,
                fn () => ['missile_rack' => new MissileRackResource($itemData)],
            ],
            $itemData->type === 'FuelIntake' || $this->hasInStdItem($itemData, 'FuelIntake') => [
                true,
                fn () => ['fuel_intake' => new FuelIntakeResource($itemData)],
            ],
            $itemData->type === 'PowerPlant' || str_contains($itemData->classification ?? '', 'PowerPlant') => [
                true,
                fn () => ['power_plant' => new PowerPlantResource($itemData)],
            ],
            $itemData->type === 'Radar' || str_contains($itemData->classification ?? '', 'Radar') => [
                true,
                fn () => ['radar' => new RadarResource($itemData)],
            ],
            $itemData->type === 'CargoGrid' || str_contains($itemData->classification ?? '', 'CargoGrid') => [
                true,
                fn () => ['cargo_grid' => new CargoGridResource($itemData)],
            ],
            $this->hasVehicleWeapon($itemData) => [
                true,
                fn () => ['vehicle_weapon' => new VehicleWeaponResource($itemData)],
            ],
            default => [false, []],
        };
    }

    protected function isTurret(ItemData $itemData): bool
    {
        return in_array($itemData->type, [
            'Turret',
            'TurretBase',
            'UtilityTurret',
            'MissileLauncher',
            'BombLauncher',
            'WeaponMount',
        ], true);
    }

    protected function addTurretData(ItemData $itemData): array
    {
        $mountName = 'max_mounts';
        if ($itemData->type === 'MissileLauncher') {
            $mountName = 'max_missiles';
        } elseif ($itemData->type === 'BombLauncher') {
            $mountName = 'max_bombs';
        }

        $ports = collect($this->extractPorts($itemData));

        return [
            $mountName => $ports->count(),
            'min_size' => $ports->min('MinSize') ?? $ports->min('min_size'),
            'max_size' => $ports->max('MaxSize') ?? $ports->max('max_size'),
        ];
    }

    private function addAttachmentPosition(ItemData $itemData): array
    {
        if ($itemData->type !== 'WeaponAttachment' || $itemData->name === '<= PLACEHOLDER =>') {
            return [false, []];
        }

        return [
            true,
            fn () => [
                'position' => match ($itemData->sub_type) {
                    'Magazine' => 'Magazine Well',
                    'Barrel' => 'Barrel',
                    'IronSight' => 'Optic',
                    'Utility' => 'Utility',
                    'BottomAttachment' => 'Underbarrel',
                    default => $itemData->sub_type,
                },
            ],
        ];
    }

    private function getTranslation(ItemData $itemData, Request $request)
    {
        $locale = $request->get('locale');

        if (! empty($locale)) {
            return $itemData->translations()->where('locale_code', $locale)->first()->translation ??
                $itemData->translations()->where('locale_code', 'en_EN')->first()->translation ??
                '';
        }

        return $itemData->translations->mapWithKeys(function (mixed $translation): array {
            if ($translation instanceof ItemTranslation) {
                return [$translation->locale_code => $translation->translation];
            }

            // Handle stdClass from tests or raw data
            return [
                $translation->locale_code ?? '' => $translation->translation ?? '',
            ];
        });
    }

    private function hasVehicleWeapon(ItemData $itemData): bool
    {
        if ($itemData->type === 'WeaponPersonal' || str_starts_with($itemData->classification ?? '', 'FPS.Weapon.')) {
            return false;
        }

        return Arr::has($itemData->data, 'stdItem.Weapon');
    }
}
