<?php

declare(strict_types=1);

namespace App\Http\Resources\Game\Item;

use App\Http\Resources\AbstractBaseResource;
use App\Http\Resources\Game\Concerns\ExtractsJsonData;
use App\Http\Resources\Game\ItemSpecification\AmmunitionResource;
use App\Http\Resources\Game\ItemSpecification\ArmorResource;
use App\Http\Resources\Game\ItemSpecification\BombResource;
use App\Http\Resources\Game\ItemSpecification\ClothingResource;
use App\Http\Resources\Game\ItemSpecification\CoolerResource;
use App\Http\Resources\Game\ItemSpecification\CounterMeasureResource;
use App\Http\Resources\Game\ItemSpecification\EmpResource;
use App\Http\Resources\Game\ItemSpecification\FlightControllerResource;
use App\Http\Resources\Game\ItemSpecification\FoodResource;
use App\Http\Resources\Game\ItemSpecification\FuelIntakeResource;
use App\Http\Resources\Game\ItemSpecification\FuelTankResource;
use App\Http\Resources\Game\ItemSpecification\GrenadeResource;
use App\Http\Resources\Game\ItemSpecification\HackingChipResource;
use App\Http\Resources\Game\ItemSpecification\JumpDriveResource;
use App\Http\Resources\Game\ItemSpecification\MedicineResource;
use App\Http\Resources\Game\ItemSpecification\MeleeWeaponResource;
use App\Http\Resources\Game\ItemSpecification\MiningLaserResource;
use App\Http\Resources\Game\ItemSpecification\MiningModifierResource;
use App\Http\Resources\Game\ItemSpecification\MiningModuleResource;
use App\Http\Resources\Game\ItemSpecification\MissileRackResource;
use App\Http\Resources\Game\ItemSpecification\MissileResource;
use App\Http\Resources\Game\ItemSpecification\PersonalWeaponResource;
use App\Http\Resources\Game\ItemSpecification\PowerPlantResource;
use App\Http\Resources\Game\ItemSpecification\QuantumDriveResource;
use App\Http\Resources\Game\ItemSpecification\QuantumInterdictionGeneratorResource;
use App\Http\Resources\Game\ItemSpecification\RadarResource;
use App\Http\Resources\Game\ItemSpecification\RadiationResistanceResource;
use App\Http\Resources\Game\ItemSpecification\SalvageModifierResource;
use App\Http\Resources\Game\ItemSpecification\SeatResource;
use App\Http\Resources\Game\ItemSpecification\SelfDestructResource;
use App\Http\Resources\Game\ItemSpecification\ShieldControllerResource;
use App\Http\Resources\Game\ItemSpecification\ShieldResource;
use App\Http\Resources\Game\ItemSpecification\SuitArmorResource;
use App\Http\Resources\Game\ItemSpecification\TemperatureResistanceResource;
use App\Http\Resources\Game\ItemSpecification\ThrusterResource;
use App\Http\Resources\Game\ItemSpecification\TractorBeamResource;
use App\Http\Resources\Game\ItemSpecification\TurretResource;
use App\Http\Resources\Game\ItemSpecification\VehicleWeaponResource;
use App\Http\Resources\Game\ItemSpecification\WeaponAttachmentResource;
use App\Http\Resources\Game\ItemSpecification\WeaponModifierResource;
use App\Http\Resources\Game\Manufacturer\ManufacturerLinkResource;
use App\Http\Resources\TranslationResolver;
use App\Models\Game\Item;
use App\Models\Game\ItemData;
use App\Services\RelatedItemsBuilder;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use OpenApi\Attributes as OA;

#[OA\Schema(
    schema: 'game_item',
    title: 'Item',
    description: 'An item in Star Citizen, based on EntityClassDefinition XML files.',
    properties: [
        new OA\Property(property: 'uuid', type: 'string'),
        new OA\Property(property: 'name', type: 'string'),
        new OA\Property(property: 'class_name', type: 'string'),
        new OA\Property(
            property: 'classification',
            description: 'Not actually found in the game data, but generated by ScDataDumper.',
            type: 'string',
            example: 'FPS.Clothing.Torso'
        ),
        new OA\Property(
            property: 'description',
            nullable: true,
            oneOf: [
                new OA\Schema(type: 'string'),
                new OA\Schema(
                    type: 'array',
                    items: new OA\Items(ref: '#/components/schemas/translation'),
                ),
            ],
        ),

        new OA\Property(
            property: 'size',
            description: 'AttachDef@Size',
            type: 'integer',
            example: 1,
            nullable: true
        ),
        new OA\Property(
            property: 'mass',
            description: 'Generated from SEntityRigidPhysicsControllerParams',
            type: 'double',
            example: 1000.0,
            nullable: true
        ),
        new OA\Property(property: 'is_base_variant', type: 'boolean'),

        new OA\Property(
            property: 'grade',
            description: 'Only returned for Ship.* items (derived formatting for ship grades).',
            type: 'string',
            nullable: true
        ),
        new OA\Property(
            property: 'class',
            description: 'Only returned for Ship.* items.',
            type: 'string',
            nullable: true
        ),

        new OA\Property(
            property: 'description_data',
            description: 'Key/value pairs derived from the item description.',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_description_data'),
            nullable: true
        ),
        new OA\Property(property: 'manufacturer_description', description: 'Manufacturer set in the description', type: 'string', nullable: true),
        new OA\Property(property: 'manufacturer', ref: '#/components/schemas/manufacturer_link', nullable: true),

        new OA\Property(property: 'type', description: 'AttachDef@Type (NOITEM_ prefix removed)', type: 'string', nullable: true),
        new OA\Property(property: 'type_web_url', description: 'Web URL for filtering items by type', type: 'string', nullable: true),
        new OA\Property(property: 'sub_type', description: 'AttachDef@SubType', type: 'string', nullable: true),

        // Attachment convenience (WeaponAttachment only)
        new OA\Property(
            property: 'position',
            description: 'Only returned for WeaponAttachment items (non-placeholder). Maps sub_type to a display slot name.',
            type: 'string',
            example: 'Optic',
            nullable: true
        ),

        // Turret-like convenience fields injected at root for turret/mount/launcher types
        new OA\Property(property: 'max_mounts', description: 'Only returned for turret-like items.', type: 'integer', nullable: true),
        new OA\Property(property: 'max_missiles', description: 'Only returned for MissileLauncher turret-like items.', type: 'integer', nullable: true),
        new OA\Property(property: 'max_bombs', description: 'Only returned for BombLauncher turret-like items.', type: 'integer', nullable: true),
        new OA\Property(property: 'min_size', description: 'Only returned for turret-like items.', type: 'integer', nullable: true),
        new OA\Property(property: 'max_size', description: 'Only returned for turret-like items.', type: 'integer', nullable: true),

        new OA\Property(property: 'dimension', ref: '#/components/schemas/item_dimension'),
        new OA\Property(property: 'inventory', ref: '#/components/schemas/item_inventory', nullable: true),

        new OA\Property(
            property: 'tags',
            description: 'AttachDef@Tags',
            type: 'array',
            items: new OA\Items(type: 'string'),
            nullable: true,
        ),
        new OA\Property(
            property: 'required_tags',
            description: 'AttachDef@RequiredTags',
            type: 'array',
            items: new OA\Items(type: 'string'),
            nullable: true,
        ),
        new OA\Property(
            property: 'entity_tags',
            description: 'Entity tag UUIDs from the database relationship (empty array when not loaded).',
            type: 'array',
            items: new OA\Items(type: 'string'),
            nullable: true,
        ),
        new OA\Property(
            property: 'entity_tag_map',
            description: 'Entity tags from the database relationship (empty array when not loaded).',
            type: 'array',
            items: new OA\Items(
                properties: [
                    new OA\Property(property: 'uuid', type: 'string'),
                    new OA\Property(property: 'name', type: 'string'),
                ],
                type: 'object'
            ),
            nullable: true,
        ),
        new OA\Property(
            property: 'interactions',
            description: 'Generated from SInteractionPointParams',
            type: 'array',
            items: new OA\Items(type: 'string'),
            nullable: true,
        ),

        // NOTE: resource returns `ports`, not `item_ports`
        new OA\Property(
            property: 'ports',
            description: 'Item ports derived from stdItem.Ports.',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_port'),
            nullable: true
        ),

        new OA\Property(property: 'heat', ref: '#/components/schemas/item_heat_connection', nullable: true),
        new OA\Property(property: 'temperature', ref: '#/components/schemas/item_temperature', nullable: true),
        new OA\Property(property: 'power', ref: '#/components/schemas/item_power_connection', nullable: true),
        new OA\Property(property: 'distortion', ref: '#/components/schemas/item_distortion', nullable: true),
        new OA\Property(property: 'durability', ref: '#/components/schemas/item_durability', nullable: true),
        new OA\Property(property: 'resource_container', ref: '#/components/schemas/resource_container', nullable: true),
        new OA\Property(property: 'resource_network', ref: '#/components/schemas/resource_network', nullable: true),
        new OA\Property(property: 'emission', ref: '#/components/schemas/item_emission', nullable: true),

        // Root-level “stdItem” blocks
        new OA\Property(property: 'seat', ref: '#/components/schemas/seat', nullable: true),
        new OA\Property(property: 'ammunition', ref: '#/components/schemas/ammunition', nullable: true),

        new OA\Property(property: 'temperature_resistance', ref: '#/components/schemas/temperature_resistance', nullable: true),
        new OA\Property(property: 'radiation_resistance', ref: '#/components/schemas/radiation_resistance', nullable: true),

        new OA\Property(property: 'armor', ref: '#/components/schemas/vehicle_armor', nullable: true),
        new OA\Property(property: 'cooler', ref: '#/components/schemas/cooler', nullable: true),
        new OA\Property(property: 'flight_controller', ref: '#/components/schemas/flight_controller', nullable: true),
        new OA\Property(property: 'fuel_tank', ref: '#/components/schemas/fuel_tank', nullable: true),
        new OA\Property(property: 'fuel_intake', ref: '#/components/schemas/fuel_intake', nullable: true),
        new OA\Property(property: 'hacking_chip', ref: '#/components/schemas/hacking_chip', nullable: true),
        new OA\Property(property: 'mining_laser', ref: '#/components/schemas/mining_laser', nullable: true),
        new OA\Property(property: 'mining_module', ref: '#/components/schemas/mining_module', nullable: true),
        new OA\Property(property: 'mining_modifier', ref: '#/components/schemas/mining_modifier', nullable: true),
        new OA\Property(property: 'mining_gadget', ref: '#/components/schemas/mining_module', description: 'Mining gadget currently resolves using the mining_module schema.', nullable: true),
        new OA\Property(property: 'quantum_drive', ref: '#/components/schemas/quantum_drive', nullable: true),
        new OA\Property(property: 'quantum_interdiction_generator', ref: '#/components/schemas/quantum_interdiction_generator', nullable: true),
        new OA\Property(property: 'self_destruct', ref: '#/components/schemas/self_destruct', nullable: true),
        new OA\Property(property: 'shield', ref: '#/components/schemas/shield', nullable: true),
        new OA\Property(property: 'shield_controller', ref: '#/components/schemas/shield_controller', nullable: true),
        new OA\Property(property: 'jump_drive', ref: '#/components/schemas/jump_drive', nullable: true),
        new OA\Property(property: 'thruster', ref: '#/components/schemas/thruster', nullable: true),
        new OA\Property(property: 'power_plant', ref: '#/components/schemas/power_plant', nullable: true),
        new OA\Property(property: 'radar', ref: '#/components/schemas/radar', nullable: true),
        new OA\Property(property: 'cargo_grid', ref: '#/components/schemas/item_inventory', nullable: true),

        // Item Specifications
        new OA\Property(
            property: 'clothing',
            description: 'Note: FPS armor currently also populates this key due to resource logic. Prefer returning suit_armor instead.',
            nullable: true,
            oneOf: [
                new OA\Schema(ref: '#/components/schemas/clothing'),
                new OA\Schema(ref: '#/components/schemas/suit_armor'),
            ],
        ),
        new OA\Property(
            property: 'suit_armor',
            ref: '#/components/schemas/suit_armor',
            description: 'FPS Armor',
            nullable: true,
        ),
        new OA\Property(property: 'bomb', ref: '#/components/schemas/bomb', nullable: true),
        new OA\Property(property: 'missile', ref: '#/components/schemas/missile', nullable: true),
        new OA\Property(property: 'missile_rack', ref: '#/components/schemas/missile_rack', nullable: true),
        new OA\Property(property: 'counter_measure', ref: '#/components/schemas/counter_measure', nullable: true),
        new OA\Property(property: 'emp', ref: '#/components/schemas/emp', nullable: true),
        new OA\Property(property: 'personal_weapon', ref: '#/components/schemas/personal_weapon', nullable: true),
        new OA\Property(property: 'vehicle_weapon', ref: '#/components/schemas/vehicle_weapon', nullable: true),
        new OA\Property(property: 'melee_weapon', ref: '#/components/schemas/melee_weapon', nullable: true),
        new OA\Property(property: 'grenade', ref: '#/components/schemas/grenade', nullable: true),
        new OA\Property(property: 'knife', ref: '#/components/schemas/melee_weapon', nullable: true, deprecated: true),
        new OA\Property(property: 'turret', ref: '#/components/schemas/turret', nullable: true),
        new OA\Property(property: 'tractor_beam', ref: '#/components/schemas/tractor_beam', nullable: true),

        new OA\Property(property: 'food', ref: '#/components/schemas/food', nullable: true),
        new OA\Property(property: 'medical', ref: '#/components/schemas/medicine', nullable: true),

        new OA\Property(property: 'weapon_modifier', ref: '#/components/schemas/weapon_modifier', nullable: true),
        new OA\Property(property: 'salvage_modifier', ref: '#/components/schemas/salvage_modifier', nullable: true),

        // WeaponAttachment: blocks are emitted as top-level keys (only when non-empty)
        new OA\Property(property: 'iron_sight', ref: '#/components/schemas/weapon_attachment_iron_sight', nullable: true),
        new OA\Property(property: 'laser_pointer', ref: '#/components/schemas/weapon_attachment_laser_pointer', nullable: true),
        new OA\Property(property: 'flashlight', ref: '#/components/schemas/weapon_attachment_flashlight', nullable: true),
        new OA\Property(property: 'magazine', ref: '#/components/schemas/weapon_attachment_magazine', nullable: true),
        new OA\Property(property: 'compensator', ref: '#/components/schemas/weapon_attachment_barrel_attachment', nullable: true),
        new OA\Property(property: 'flash_hider', ref: '#/components/schemas/weapon_attachment_barrel_attachment', nullable: true),

        new OA\Property(property: 'base_variant', ref: '#/components/schemas/item_link', nullable: true),
        new OA\Property(
            property: 'variants',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_link'),
            nullable: true
        ),

        new OA\Property(
            property: 'related_items',
            ref: '#/components/schemas/item_related_items',
            description: 'Only returned when `include=related_items` is requested.',
            nullable: true
        ),

        new OA\Property(
            property: 'shops',
            description: 'Deprecated: shop data is not available in the source files anymore.',
            type: 'array',
            items: new OA\Items(type: 'object'),
            nullable: true,
            deprecated: true
        ),

        new OA\Property(property: 'web_url', description: 'Web URL for item detail page', type: 'string'),
        new OA\Property(property: 'link', description: 'API URL for item detail endpoint', type: 'string'),

        new OA\Property(
            property: 'updated_at',
            description: 'Date/time this item was updated in the database.',
            type: 'string',
            format: 'date-time',
        ),
        new OA\Property(
            property: 'version',
            description: 'Game version code',
            type: 'string',
            example: '4.4.0-LIVE.12340123'
        ),
    ],
    type: 'object'
)]
#[OA\Schema(
    schema: 'item_related_link',
    title: 'Related Item Link',
    description: 'Minimal link information for a related item',
    properties: [
        new OA\Property(property: 'uuid', type: 'string'),
        new OA\Property(property: 'name', type: 'string'),
        new OA\Property(property: 'variant_name', type: 'string', nullable: true),
        new OA\Property(property: 'link', type: 'string'),
    ],
    type: 'object'
)]
#[OA\Schema(
    schema: 'item_related_link_ext',
    title: 'Related Item Link (Extended)',
    description: 'Related item link with basic classification',
    allOf: [
        new OA\Schema(ref: '#/components/schemas/item_related_link'),
        new OA\Schema(
            properties: [
                new OA\Property(property: 'type', type: 'string', nullable: true),
                new OA\Property(property: 'sub_type', type: 'string', nullable: true),
            ],
            type: 'object'
        ),
    ],
)]
#[OA\Schema(
    schema: 'item_related_items',
    title: 'Related Items',
    description: 'Aggregated related information for base/variants and set items',
    properties: [
        new OA\Property(property: 'set_name', type: 'string', nullable: true),
        new OA\Property(property: 'base_item', ref: '#/components/schemas/item_related_link', nullable: true),
        new OA\Property(
            property: 'variant_items',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_related_link'),
            nullable: true,
        ),
        new OA\Property(
            property: 'set_items',
            type: 'array',
            items: new OA\Items(ref: '#/components/schemas/item_related_link_ext'),
            nullable: true,
        ),
    ],
    type: 'object'
)]
class ItemResource extends AbstractBaseResource
{
    use ExtractsJsonData;

    public static function validIncludes(): array
    {
        return [
            'variants',
        ];
    }

    public function toArray(Request $request): array
    {
        if ($this->uuid === null) {
            return [];
        }

        $this->addMetadata('deprecated_fields', [
            'shops' => 'Shop data is not available in the source files anymore, there is currently no replacement.',
        ]);

        $itemData = $this->data->first();

        // Determine if 'related_items' has been requested via include
        $includeParam = $request->query('include');
        $includeValues = [];
        if (is_string($includeParam)) {
            $includeValues = array_map('trim', explode(',', $includeParam));
        } elseif (is_array($includeParam)) {
            $includeValues = $includeParam;
        }
        $includeRelated = in_array('related_items', $includeValues, true);

        $type = str_replace('NOITEM_', '', ($itemData->type ?? ''));

        return [
            'uuid' => $this->uuid,
            'name' => $itemData->name,
            'class_name' => $itemData->class_name,
            'classification' => $itemData->classification,
            'description' => $this->getTranslation($this->resource, $request),
            'size' => $itemData->size,
            'mass' => $this->extractNumeric($itemData, 'Mass'),
            'is_base_variant' => $itemData->base_id === null,
            $this->mergeWhen(str_starts_with($itemData->classification ?? '', 'Ship.'), [
                'grade' => $this->formatGrade($itemData),
                'class' => $itemData->class,
            ]),
            'description_data' => ItemDescriptionDataResource::collection($itemData->descriptionData),
            'manufacturer_description' => $itemData->getDescriptionDatum('Manufacturer'),
            'manufacturer' => $itemData->relationLoaded('manufacturer')
                ? new ManufacturerLinkResource($itemData->manufacturer)
                : null,
            'type' => $type,
            'type_web_url' => $this->buildTypeWebUrl($type, $request),
            'sub_type' => $itemData->sub_type,
            $this->mergeWhen(...$this->addAttachmentPosition($itemData)),
            $this->mergeWhen($this->isTurret($itemData), $this->addTurretData($itemData)),
            $this->mergeWhen(...$this->addSpecification($this->resource, $itemData)),

            'dimension' => new ItemDimensionResource($itemData),

            $this->mergeWhen($this->hasInStdItem($itemData, 'InventoryContainer'), [
                'inventory' => new ItemInventoryResource($this->extractFromStdItem($itemData, 'InventoryContainer')),
            ]),

            'tags' => $this->extractArray($itemData, 'Tags'),
            'required_tags' => $this->extractArray($itemData, 'RequiredTags'),
            'entity_tags' => $itemData->relationLoaded('entityTags')
                ? $itemData->entityTags->pluck('uuid')->values()->toArray()
                : [],
            'entity_tag_map' => $itemData->relationLoaded('entityTags')
                ? $itemData->entityTags->map(fn ($tag) => [
                    'uuid' => $tag->uuid,
                    'name' => $tag->name,
                ])->values()->toArray()
                : [],
            'interactions' => $this->extractArray($itemData, 'Interactions'),
            'ports' => ItemPortResource::collection($this->when($this->hasInStdItem($itemData, 'Ports'), $this->extractPorts($itemData))),
            $this->mergeWhen($this->hasInStdItem($itemData, 'ResourceContainer'), [
                'resource_container' => new ResourceContainerResource($this->extractFromStdItem($itemData, 'ResourceContainer')),
            ]),

            $this->mergeWhen($this->hasInStdItem($itemData, 'RadiationResistance'), [
                'radiation_resistance' => new RadiationResistanceResource($this->extractFromStdItem($itemData, 'RadiationResistance')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'TemperatureResistance'), [
                'temperature_resistance' => new TemperatureResistanceResource($this->extractFromStdItem($itemData, 'TemperatureResistance')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'HeatConnection'), [
                'heat' => new ItemHeatConnectionResource($this->extractFromStdItem($itemData, 'HeatConnection')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'Temperature'), [
                'temperature' => new ItemTemperatureResource($this->extractFromStdItem($itemData, 'Temperature')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'PowerConnection'), [
                'power' => new ItemPowerConnectionResource($this->extractFromStdItem($itemData, 'PowerConnection')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'Durability') && $this->extractFromStdItem($itemData, 'Durability.Health', 0) > 0, [
                'durability' => new ItemDurabilityResource($this->extractFromStdItem($itemData, 'Durability')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'Distortion'), [
                'distortion' => new ItemDistortionResource($this->extractFromStdItem($itemData, 'Distortion')),
            ]),
            $this->mergeWhen($this->hasInStdItem($itemData, 'ResourceNetwork'), [
                'resource_network' => new ResourceNetworkResource($itemData),
                'emission' => new ItemEmissionResource($this->extractFromStdItem($itemData, 'Emission')),
            ]),

            'shops' => [],
            $this->mergeWhen($itemData->base_id !== null && $itemData->relationLoaded('baseVariant'), [
                'base_variant' => new ItemLinkResource($itemData->baseVariant),
            ]),
            'variants' => $itemData->relationLoaded('variants')
                ? ItemLinkResource::collection(
                    $itemData->variants
                        ->filter(fn ($variant) => $variant->item !== null)
                )
                : [],
            $this->mergeWhen(
                $includeRelated && $itemData->relationLoaded('gameVersion'),
                fn () => [
                    'related_items' => (new RelatedItemsBuilder($itemData->gameVersion->code))->build($this->resource),
                ]
            ),
            'web_url' => $this->buildWebUrl($request),
            'link' => route('items.show', ['identifier' => $this->uuid]),
            'updated_at' => $this->updated_at,
            'version' => $itemData->relationLoaded('gameVersion')
                ? $itemData->gameVersion->code
                : null,
        ];
    }

    protected function addSpecification(Item $item, ItemData $itemData): array
    {
        $specifications = [];
        $hasMatch = false;

        // FPS Clothing
        if (str_starts_with($itemData->classification ?? '', 'FPS.Clothing.')) {
            $hasMatch = true;
            $specifications['clothing'] = static fn () => new ClothingResource($itemData);

            $this->addMetadata('deprecated_fields', [
                'clothing' => [
                    'clothing_type' => 'Use type instead.',
                    'temp_resistance_min' => 'Use temperature_resistance from root.',
                    'temp_resistance_max' => 'Use temperature_resistance from root.',
                ],
            ]);
        }

        // FPS Armor
        if (str_starts_with($itemData->classification ?? '', 'FPS.Armor.')) {
            $hasMatch = true;
            $specifications['clothing'] = static fn () => new SuitArmorResource($itemData);
            $specifications['suit_armor'] = static fn () => new SuitArmorResource($itemData);
        }

        // Ship Armor
        if (str_starts_with($itemData->classification ?? '', 'Ship.Armor.')) {
            $hasMatch = true;
            $specifications['armor'] = static fn () => new ArmorResource($itemData);

            $this->addMetadata('deprecated_fields', [
                'armor' => [
                    'signal_infrared' => 'Use signal_multiplier.infrared instead.',
                    'signal_electromagnetic' => 'Use signal_multiplier.electromagnetic instead.',
                    'signal_cross_section' => 'Use signal_multiplier.cross_section instead.',
                    'damage_physical' => 'Use damage_multiplier.physical instead.',
                    'damage_energy' => 'Use damage_multiplier.energy instead.',
                    'damage_distortion' => 'Use damage_multiplier.distortion instead.',
                    'damage_thermal' => 'Use damage_multiplier.thermal instead.',
                    'damage_biochemical' => 'Use damage_multiplier.biochemical instead.',
                    'damage_stun' => 'Use damage_multiplier.stun instead.',
                ],
            ]);
        }

        // Thrusters
        if (str_starts_with($itemData->classification ?? '', 'Ship.MainThruster') ||
            str_starts_with($itemData->classification ?? '', 'Ship.ManneuverThruster')) {
            $hasMatch = true;
            $specifications['thruster'] = static fn () => new ThrusterResource($itemData);
        }

        // Flight Controller
        if ($itemData->type === 'FlightController') {
            $hasMatch = true;
            $specifications['flight_controller'] = static fn () => new FlightControllerResource($itemData);
        }

        // Fuel Tanks
        if (in_array($itemData->type, ['FuelTank', 'QuantumFuelTank', 'ExternalFuelTank'], true)) {
            $hasMatch = true;
            $specifications['fuel_tank'] = static fn () => new FuelTankResource($itemData);
        }

        // Hacking Chip
        if ($itemData->sub_type === 'Hacking') {
            $hasMatch = true;
            $specifications['hacking_chip'] = static fn () => new HackingChipResource($itemData);
        }

        // Mining Laser
        if ($itemData->type === 'WeaponMining') {
            $hasMatch = true;
            $specifications['mining_laser'] = static fn () => new MiningLaserResource($itemData);
        }

        // Mining Module/Modifier
        if ($itemData->type === 'MiningModifier') {
            $hasMatch = true;
            $specifications['mining_module'] = static fn () => new MiningModuleResource($itemData);

            $this->addMetadata('deprecated_fields', [
                'mining_module' => 'Use mining_modifier instead.',
            ]);
        }

        // Mining Gadget
        if ($itemData->type === 'Gadget' && $this->extractFromStdItem($itemData, 'MiningModule') !== null) {
            $hasMatch = true;
            $specifications['mining_gadget'] = static fn () => new MiningModuleResource($itemData);
        }

        // Quantum Drive
        if ($itemData->type === 'QuantumDrive') {
            $hasMatch = true;
            $specifications['quantum_drive'] = static fn () => new QuantumDriveResource($itemData);
        }

        // Quantum Interdiction Generator
        if ($itemData->type === 'QuantumInterdictionGenerator') {
            $hasMatch = true;
            $specifications['quantum_interdiction_generator'] = static fn () => new QuantumInterdictionGeneratorResource($itemData);
        }

        // Self Destruct
        if ($itemData->type === 'SelfDestruct') {
            $hasMatch = true;
            $specifications['self_destruct'] = static fn () => new SelfDestructResource($itemData);
        }

        // Bombs
        if ($itemData->type === 'Bomb') {
            $hasMatch = true;
            $specifications['bomb'] = static fn () => new BombResource($itemData);

            $this->addMetadata('deprecated_fields', [
                'bomb' => [
                    'explosion_safety_distance' => 'Use explosion.safety_distance instead.',
                    'explosion_radius_min' => 'Use explosion.radius_min instead.',
                    'explosion_radius_max' => 'Use explosion.radius_max instead.',
                    'damage' => 'Use damage_total instead.',
                    'damages' => 'Use damage_map instead.',
                ],
            ]);
        }

        // Missiles/Torpedoes
        if ($itemData->type === 'Torpedo' || $itemData->type === 'Missile') {
            $hasMatch = true;
            $specifications['missile'] = static fn () => new MissileResource($itemData);
        }

        // EMP
        if ($itemData->type === 'EMP') {
            $hasMatch = true;
            $specifications['emp'] = static fn () => new EmpResource($itemData);
        }

        // Cooler
        if ($itemData->type === 'Cooler') {
            $hasMatch = true;
            $specifications['cooler'] = static fn () => new CoolerResource($itemData);
        }

        // Turet
        if ($itemData->type === 'Turret') {
            $hasMatch = true;
            $specifications['turret'] = static fn () => new TurretResource($itemData);
        }

        // Tractor/Towing Beam
        if (in_array($itemData->type, ['TractorBeam', 'TowingBeam'], true)) {
            $hasMatch = true;
            $specifications['tractor_beam'] = static fn () => new TractorBeamResource($itemData);
        }

        // Shield
        if ($itemData->type === 'Shield') {
            $hasMatch = true;
            $specifications['shield'] = static fn () => new ShieldResource($itemData);
        }

        // Shield Controller
        if ($itemData->type === 'ShieldController') {
            $hasMatch = true;
            $specifications['shield_controller'] = static fn () => new ShieldControllerResource($itemData);
        }

        // Jump Drive
        if ($itemData->type === 'JumpDrive') {
            $hasMatch = true;
            $specifications['jump_drive'] = static fn () => new JumpDriveResource($itemData);
        }

        // Grenade (has both grenade and personal_weapon specs)
        if ($itemData->type === 'WeaponPersonal' && $itemData->sub_type === 'Grenade') {
            $hasMatch = true;
            $specifications['grenade'] = static fn () => new GrenadeResource($itemData);
            $specifications['personal_weapon'] = static fn () => new PersonalWeaponResource($itemData);

        }

        // Knife/Melee Weapon
        if ($itemData->type === 'WeaponPersonal' && $itemData->sub_type === 'Knife') {
            $hasMatch = true;
            $specifications['melee_weapon'] = static fn () => new MeleeWeaponResource($itemData);
            $specifications['knife'] = static fn () => new MeleeWeaponResource($itemData);
        }

        // Personal Weapon (general - after specific grenade/knife checks)
        if (($itemData->type === 'WeaponPersonal' || str_starts_with($itemData->classification ?? '', 'FPS.Weapon.')) &&
            ! isset($specifications['grenade']) && ! isset($specifications['melee_weapon'])) {
            $hasMatch = true;
            $specifications['personal_weapon'] = static fn () => new PersonalWeaponResource($itemData);

            $this->addMetadata('deprecated_fields', [
                'personal_weapon' => [
                    'rof' => 'Use rpm instead',
                    'effective_range' => 'Use range instead',
                    'magazine_size' => 'Use capacity instead',
                    'damage_per_shot' => 'Use damage.alpha_total instead',
                ],
            ]);
        }

        // Salvage Modifier
        if ($this->hasInStdItem($itemData, 'SalvageModifier')) {
            $hasMatch = true;
            $specifications['salvage_modifier'] = static fn () => new SalvageModifierResource($itemData);
        }

        // Weapon Modifier
        if ($this->hasInStdItem($itemData, 'WeaponModifier')) {
            $hasMatch = true;
            $specifications['weapon_modifier'] = static fn () => new WeaponModifierResource($itemData);

            $this->addMetadata('deprecated_fields', [
                'weapon_modifier' => [
                    'fire_rate_multiplier' => 'use `base.fire_rate_multiplier` instead.',
                    'damage_multiplier' => 'use `base.damage_multiplier` instead.',
                    'damage_over_time_multiplier' => 'use `base.damage_over_time_multiplier` instead.',
                    'projectile_speed_multiplier' => 'use `base.projectile_speed_multiplier` instead.',
                    'ammo_cost_multiplier' => 'use `base.ammo_cost_multiplier` instead.',
                    'heat_generation_multiplier' => 'use `base.heat_generation_multiplier` instead.',
                    'sound_radius_multiplier' => 'use `base.sound_radius_multiplier` instead.',
                    'charge_time_multiplier' => 'use `base.charge_time_multiplier` instead.',
                ],
            ]);
        }

        // Weapon Attachment
        if ($itemData->type === 'WeaponAttachment' || $this->hasInStdItem($itemData, 'WeaponAttachment')) {
            $hasMatch = true;

            $attachment = (new WeaponAttachmentResource($itemData))->resolve();

            foreach ($attachment as $key => $data) {
                $specifications[$key] = static fn () => $data;
            }
        }

        // Food/Drink
        if (in_array($itemData->type, ['Food', 'Bottle', 'Drink'], true) || $this->hasInStdItem($itemData, 'Food')) {
            $hasMatch = true;
            $specifications['food'] = static fn () => new FoodResource($itemData);
        }

        // Medicine
        if ($this->hasInStdItem($itemData, 'Medical')) {
            $hasMatch = true;
            $specifications['medical'] = static fn () => new MedicineResource($itemData);
        }

        // Countermeasures
        if ($itemData->type === 'WeaponDefensive' || str_contains($itemData->classification ?? '', 'WeaponDefensive')) {
            $hasMatch = true;
            $specifications['counter_measure'] = static fn () => new CounterMeasureResource($itemData);
        }

        // Missile Rack
        if (($itemData->type === 'MissileLauncher' && $itemData->sub_type === 'MissileRack') ||
            str_contains($itemData->classification ?? '', 'MissileRack')) {
            $hasMatch = true;
            $specifications['missile_rack'] = static fn () => new MissileRackResource($itemData);
        }

        // Fuel Intake
        if ($itemData->type === 'FuelIntake' || $this->hasInStdItem($itemData, 'FuelIntake')) {
            $hasMatch = true;
            $specifications['fuel_intake'] = static fn () => new FuelIntakeResource($itemData);
        }

        // Power Plant
        if ($itemData->type === 'PowerPlant' || str_contains($itemData->classification ?? '', 'PowerPlant')) {
            $hasMatch = true;
            $specifications['power_plant'] = static fn () => new PowerPlantResource($itemData);
        }

        // Radar
        if ($itemData->type === 'Radar' || str_contains($itemData->classification ?? '', 'Radar')) {
            $hasMatch = true;
            $specifications['radar'] = static fn () => new RadarResource($itemData);
        }

        // Cargo Grid
        if ($itemData->type === 'CargoGrid' || str_contains($itemData->classification ?? '', 'CargoGrid')) {
            $hasMatch = true;
            $specifications['cargo_grid'] = static fn () => new ItemInventoryResource($itemData);
        }

        // Vehicle Weapon
        if ($this->hasVehicleWeapon($itemData)) {
            $hasMatch = true;
            $specifications['vehicle_weapon'] = static fn () => new VehicleWeaponResource($itemData);
        }

        if ($this->hasInStdItem($itemData, 'Seat')) {
            $hasMatch = true;
            $specifications['seat'] = static fn () => new SeatResource($itemData);
        }

        if ($this->hasInStdItem($itemData, 'Ammunition')) {
            $hasMatch = true;
            $specifications['ammunition'] = static fn () => new AmmunitionResource($itemData);

            $this->addMetadata('deprecated_fields', [
                'ammunition' => [
                    'impact_damage' => 'Use impact_damage_map instead.',
                    'detonation_damage' => 'Use detonation_damage_map instead.',
                ],
            ]);
        }

        if ($this->hasInStdItem($itemData, 'MiningModule')) {
            $hasMatch = true;
            $specifications['mining_modifier'] = static fn () => new MiningModifierResource($itemData);
        }

        if (! $hasMatch) {
            return [false, []];
        }

        return [
            true,
            fn () => $this->resolveSpecifications($specifications),
        ];
    }

    private function resolveSpecifications(array $specifications): array
    {
        return array_map(
            static fn ($spec) => is_callable($spec) ? $spec() : $spec,
            $specifications
        );
    }

    protected function isTurret(ItemData $itemData): bool
    {
        return in_array($itemData->type, [
            'Turret',
            'TurretBase',
            'UtilityTurret',
            'MissileLauncher',
            'BombLauncher',
            'WeaponMount',
        ], true);
    }

    protected function addTurretData(ItemData $itemData): array
    {
        $mountName = 'max_mounts';
        if ($itemData->type === 'MissileLauncher') {
            $mountName = 'max_missiles';
        } elseif ($itemData->type === 'BombLauncher') {
            $mountName = 'max_bombs';
        }

        $ports = collect($this->extractPorts($itemData));

        return [
            $mountName => $ports->count(),
            'min_size' => $ports->min('MinSize') ?? $ports->min('min_size'),
            'max_size' => $ports->max('MaxSize') ?? $ports->max('max_size'),
        ];
    }

    private function addAttachmentPosition(ItemData $itemData): array
    {
        if ($itemData->type !== 'WeaponAttachment' || $itemData->name === '<= PLACEHOLDER =>') {
            return [false, []];
        }

        return [
            true,
            fn () => [
                'position' => match ($itemData->sub_type) {
                    'Magazine' => 'Magazine Well',
                    'Barrel' => 'Barrel',
                    'IronSight' => 'Optic',
                    'Utility' => 'Utility',
                    'BottomAttachment' => 'Underbarrel',
                    default => $itemData->sub_type,
                },
            ],
        ];
    }

    private function getTranslation(Item $item, Request $request): array|string|null
    {
        return TranslationResolver::resolve($item, $request);
    }

    private function hasVehicleWeapon(ItemData $itemData): bool
    {
        if ($itemData->type === 'WeaponPersonal' || str_starts_with($itemData->classification ?? '', 'FPS.Weapon.')) {
            return false;
        }

        return Arr::has($itemData->data, 'stdItem.Weapon');
    }

    private function buildWebUrl(Request $request): string
    {
        $url = route('web.items.show', ['item' => $this->uuid]);
        $version = $request->query('version');

        if ($version === null || $version === '') {
            return $url;
        }

        return url()->query($url, ['version' => $version]);
    }

    private function buildTypeWebUrl(string $type, Request $request): ?string
    {
        if ($type === '') {
            return null;
        }

        $url = route('web.items.index', ['filter' => ['type' => $type]]);
        $version = $request->query('version');

        if ($version === null || $version === '') {
            return $url;
        }

        return url()->query($url, ['version' => $version]);
    }

    private function formatGrade(ItemData $itemData): mixed
    {
        if (! str_starts_with($itemData->classification ?? '', 'Ship.')) {
            return $itemData->grade;
        }

        return match ($itemData->grade) {
            1 => 'A',
            2 => 'B',
            3 => 'C',
            4 => 'D',
            default => $itemData->grade,
        };
    }
}
