name: Lint Code Base

on:
  push:
    branches: [ develop, "feature/**" ]
  pull_request:
    branches: [ develop, main ]

jobs:
  php-lint:
    name: PHP (Composer + Pint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer
          extensions: gd, pdo, session, fileinfo, xml

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Pint
        run: ./vendor/bin/pint --test
